### ISSUE TITLE
CreateDevice failed with error: "push provider "" with type "firebase" not found"

### ISSUE THREAD

**Issue by arizonal2014** [GetStream/stream-chat-js#1036]
Hello there!

on calling "updateToken" method below, a DioErrorType.response  is produced  DioErrorType.response 

    **_{ 
       code: 4, 
     message: "CreateDevice failed with error: "push provider "" with type "firebase" not found"", 
     StatusCode: 400, 
       duration: "0.00ms", 
        more_info: "https://getstream.io/chat/docs/api_errors_response" 
   }_** 

` FutureOr updateToken(String? firebaseToken) {
    print('Token.........$firebaseToken');
    StreamChat.of(context)
        .client
        .addDevice(firebaseToken!, PushProvider.firebase);
    setState(() {
      firebaseToke = firebaseToken;
    });
  }
`
I will appreciate any suggestion on the below error. I found this issue https://github.com/GetStream/stream-chat-js/issues/1005
but I am using flutter SDK

**Comment by ferhatelmas** [comment]
`UpdateAppSettings` endpoint configuration is nameless because it can have one provider type per app (unique).
`UpsertPushProvider` endpoint configuration is named because apps can have multiple of same provider such as dev, staging, production, etc.

In total, all configs are put into app push providers property and while adding a device, existence of config is checked. According to error message, it seems you didn't add a nameless config (via UpdateAppSettings) but tried to create a device without giving provider name.If you give a provider name in your request, it should be fine. For the good snippet, see flutter docs.https://getstream.io/chat/docs/sdk/flutter/guides/adding_push_notifications/#introduction

As a side note, dashboard creates new configs via `UpsertPushProvider` so with a name. Please let us know if anything else is needed.

**Comment by arizonal2014** [comment]
Thanks for your reply. It was very helpful.
