### ISSUE TITLE
APNS templates not working

### ISSUE THREAD

**Issue by mfbx9da4** [GetStream/stream-chat-js#1164]
We've been forced to upgrade to push notifications v2 and I'm trying to configure APNS templates for it. However, there is no way in the dashboard and using the admin sdk to update the push provider does not work.

**Comment by sgowda97** [comment]
We are facing the same issue. Any fix for this?

**Comment by gc0rtes** [comment]
Hi,
Unfortunately, Push Notification v1 has been discontinued due to FCM's gradual shutdown of the deprecated APIs we used in the V1 system. Please reach out to support via [this link](https://getstream.io/contact/support/) so we can guide you through the migration process. When reporting the issue, please include:

- Stream App ID
- SDK and version
- The error from the API
- Any other relevant information

Thank you!

Guilherme Cortes
Integration Support Engineer at Stream
