### ISSUE TITLE
bug: unread count number show do not correct after unmute channel

### ISSUE THREAD

**Issue by minhth-1529** [GetStream/stream-chat-js#1294]
**Describe the bug**

I received message from other user A, I muted that channel, user A still send message, I unmute that channel, unread count number show do not correct.

**To Reproduce**

https://github.com/GetStream/stream-chat-react/assets/17897146/29965ed9-69a3-4f79-88c4-e94d3725ef95

**Expected behavior**

show correct unread count number after unmute

**Package version**
- stream-chat-react: ^11.17.0
- stream-chat-css: ^4.15.0
- stream-chat-js: ^8.30.0

**Comment by MartinCupela** [comment]
@minhth-1529 the logic related to what happens when a user is muted is up the integrators. Please see the [API docs here](https://getstream.io/chat/docs/javascript/moderation/?language=javascript&q=mute%20user#mutes)

<img width="831" alt="image" src="https://github.com/GetStream/stream-chat-js/assets/32706194/51d47f16-8efa-46e1-a59b-4e012cf0fc04">
