### ISSUE TITLE
System message realted question

### ISSUE THREAD

**Issue by ao-alex** [GetStream/stream-chat-js#1371]
Hi all,
I have a question related to system messages, is it possible to send system message but not silent, so unread count is increased?
Can't find anything in docs.

**Comment by szuperaz** [comment]
Hi,

Sorry for the late response. System messages are not silent (unless marked with `silent: true`) ([docs](https://getstream.io/chat/docs/javascript/silent_messages/?language=javascript&q=system%20messages)). However, the `stream-chat-js` package had a bug, and system messages were handled as silent messages. This bug was fixed in version [8.40.1](https://github.com/GetStream/stream-chat-js/releases/tag/v8.40.1). If you update to that version, you should have the desired behavior.

I'm going to close this ticket, but feel free to reopen it if system messages don't work as expected for you and we can take a deeper look.
