### ISSUE TITLE
channel.data is sometimes an empty object after creating a channel

### ISSUE THREAD

**Issue by veloware** [GetStream/stream-chat-js#421]
I am creating a channel, server-side - 

```
    const channelId = short.generate();
    const data = {
      members: [createdBy, ...invites],
      invites,
      created_by: { id: createdBy },
    };
    await this.client
      .channel(CustomChannelTypes.call, channelId, data)
      .create();
    return channelId;
```

then after that, on the client I am calling - 

```
const channel = await client.channel(ChannelTypes.call, channelId);
```

_Sometimes_ `channel.data` is `{}` - 

<img width="284" alt="Screenshot 2020-09-09 at 15 05 37" src="https://user-images.githubusercontent.com/61578546/92609046-01ffe400-f2ae-11ea-9f38-cca92083f457.png">

and sometimes it is there - 

<img width="885" alt="Screenshot 2020-09-09 at 15 05 50" src="https://user-images.githubusercontent.com/61578546/92609076-0a581f00-f2ae-11ea-90ed-7a397fda810c.png">

Is the population of `data` async or something?  I am looking to get, _reliably_, the creator of the channel

gz#5877

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/5877'>Zendesk ticket #5877</a>:<br><br>Client-side you'll want to be using queryChannels() instead of `const channel = await client.channel(ChannelTypes.call, channelId);`​ because that's instantiating a new channel without a data object.
