### ISSUE TITLE
Monorepos for GetStream

### ISSUE THREAD

**Issue by giautm** [GetStream/stream-chat-js#435]
There are three projects:
- https://github.com/GetStream/stream-chat-js
- https://github.com/GetStream/stream-chat-react-native (contains 3 packages: core, expo, native)
- https://github.com/GetStream/stream-chat-react

A lot of logic was duplicated between stream-chat-react & stream-chat-react-native. You should consider to merge them into a single repository (mono-repo) for sharing hooks/logic cross projects. And manage dependencies correctly, for example project see: https://github.com/react-navigation/react-navigation

gz#6124

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/6124'>Zendesk ticket #6124</a>:<br><br>Hi Giautm

Thanks for the suggestion. Appreciate it.

Cheers
Seetha

**Comment by shodgetts** [comment]
Agent comment from Vishal Narkhede in <a href='https://getstream.zendesk.com/agent/tickets/6124'>Zendesk ticket #6124</a>:<br><br>Hey,

Thanks for the suggestion. But at the moment, brining all the repos under mono-repo or sharing code between react and react-native is not a viable solution for us, because of maintenance overhead that comes with it and insignificant overlap between react and react-native sdk.

Closing this ticket for now. Please reopen if you have any more questions.


Thanks,
Vishal
