### ISSUE TITLE
Token doesn't regenerates after expiration

### ISSUE THREAD

**Issue by vtereshyn** [GetStream/stream-chat-js#539]
I use server-side token generating. When I receive an error from the server about token expiration I do re-fetch of the token, but always get the same value. The only case when I get a new token value is restarting of my server. 

```
const client = new StreamChat("API_key", "API_secret");
return client.createToken("user_id_here", 2000);
```

This code will return the same token every time when function calls. 

NOTE: I am not using REST on my server, I'm using GraphQL if it can be issue.

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/7905'>Zendesk ticket #7905</a>:<br><br>Hi,

Thanks for reaching out! I am looking into this for you now and will be in touch shortly.

Best,
Ryan

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/7905'>Zendesk ticket #7905</a>:<br><br>Hi,

This is expected behavior as per our docs, please take a look here. If you would like to have a new token each time you request one, then you will want to create a function or class that you implement and that is responsible for requesting a new token. By default, user tokens are valid indefinitely, so if you don’t have a reason for token expiration, you can remove the “2000” from your code and it will run just fine. Please let me know if you have any other questions here!


Best,
Ryan

**Comment by vtereshyn** [comment]
Thanks for your responding

But still, this is not clear to me why your `createToken` function which accepts `expiration time` parameter always returns the same value.
My client fetchs API to get new token if it's expired, but `createToken` returns old value again and again. This is definitely an issue
