### ISSUE TITLE
How to manage channel-user membership efficiently in a large app?

### ISSUE THREAD

**Issue by agaace** [GetStream/stream-chat-js#574]
Hello,
I have a large multitenant app. Let's say my typical team size will be 1,000 users and 50 channels. How can I efficiently manage users and channels in such a large app?

Scenario 1:
Adding channel #51 that will be public and visible for everyone. So I want to add all existing 1,000 users as members of channel #51.

Solution:
Looks like I will have to fetch all exiting members in chunks of 100 from one of the existing channels with `channel.queryMembers`, then for each chunk call `channel.addMembers` in a loop?

```js
const newChannel = client.channel({...}).create();
for (let offset = 0; offset < 1000; offset += 100) {
  const members = (await existingChannel.queryMembers({}, {}, { limit:100, offset: offset }).members;
  const memberIds = members.map((member) => member.id));
  await channel.addMembers(memberIds);
}
```

That's not an acceptable solution. That's 101 API calls to create a channel when there's already 50 channels and will grow linearly with both channel and user count..

Is there a better way to create a new channel and copy over members from another channel in like a single API call? Or a way to implement public channels that will still be enumerable and viewable by everyone even if they're not members, and where they will still get notifications about unread messages?

Scenario 2:
Adding a new user #1,001 and automatically adding them as a member to existing 50 channels (combination of public and private channels).

Solution:
Looks like I will have to call `channel.addMembers` in a loop for each and every channel?

```js
const newUser = await client.connectUser({...});
let channels = await streamApi.queryChannels({ team: teamId }, {}, {});
for (const channel of channels) await channel.addMembers([newUser]);
```

Again, that's not an acceptable solution. If I need to add a user to 50 channels, I am forced to make 51 API calls. And it will grow linearly with the number of channels.

So what is the proper way of doing this efficiently without hitting our API rate quota hard every time someone creates a new user account and gets added to a bunch of channels?

Is Stream Chat even designed to work with large amounts of users and channels like in these scenarios, or am I trying to push it beyond what it was designed to do?

 

gz#8388

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/8388'>Zendesk ticket #8388</a>:<br><br>Hi

Thanks for the details.
We will check this and get back to you soon.

Cheers
Seetha

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/8388'>Zendesk ticket #8388</a>:<br><br>Unfortunately, this is a situation where our API does not perfectly fit the use case. That being said, there is still a scalable solution here. Instead of making API calls within loops, I'd recommend using multi tenancy (as you are) & open channels in tandem with our webhooks to send your notifications: https://getstream.io/chat/docs/webhooks_overview/?language=js. Our push system doesn’t cater to this because of the membership requirement so this is a good alternative. However, this does mean that unread counts will not be available. I hope that this clears things up for you.
