### ISSUE TITLE
User unable to set user to invisible

### ISSUE THREAD

**Issue by chenghw** [GetStream/stream-chat-js#643]
Hi,

I'm trying to use the [invisible](https://getstream.io/chat/docs/presence_format/?language=js#invisible) feature but can't seem to get it working properly.

```javascript
// Docs have this code snippet for JS, which I'm assuming is missing the token as a second argument

// mark a user as invisible
await client.setUser({
    id: 'unique_user_id',
    invisible: true
});

// This resolve of this is a user but the invisible property is false
````

The behavior I'm trying to create is where I'd be signed in and I can turn myself invisible. However the `setUser` method checks if I've already set my user and errors out telling me to disconnect first. When I disconnect and try to set my user again I get an error `You can't use a channel after client.disconnect() was called` which I believe this issue covers https://github.com/GetStream/stream-chat-react/issues/546

I try initially setting my user to invisible true, however I still get the returned object as invisible false(stated above in the code snippet) and other users are able to see that I'm online.

Am I approaching this correctly or is invisible currently not fully supported?

Versions
"stream-chat": "2.8.0"
"stream-chat-react": "3.2.3"

gz#7481

**Comment by miagilepner** [comment]
Hi @chenghw, @SSTPIERRE2. I'm sorry this took so long to get fixed. The invisible feature is now working properly. You can use the `upsertUser` method in order to modify the invisibility status of the client: https://getstream.io/chat/docs/react/presence_format/?language=javascript#invisible. Please feel free to open another issue if this isn't working as you expect.
