### ISSUE TITLE
[Help] Snapstreak ?

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-js#650]
Hey,

Im trying to add pseudo Snapstreak to my chat: [https://support.snapchat.com/fr-FR/a/snapstreaks](https://support.snapchat.com/fr-FR/a/snapstreaks)

The idea is to run a batch everyday, which increment a counter/chat if all members write a message/day

I check the API, i have no easy and performant way to do this (only group < 10 will be checked every day).

Do you have any internal method/API that can help ?

Thank you,
Nelson

gz#10299

-----

for now, im starting collecting data from afterSend trigger in my own DB...

**Comment by shodgetts** [comment]
Hello, Stream Customer Success here. So this feature is obviously not something that is built into the product and the information regarding who is on a "streak" with whom is not stored. However, the channel itself may have all of the data you need in order to know who is on a "streak" with who. You could compare message send dates to see if two have been sent in the last 24 hours or so. Alternatively, you may wish to store this data on your side and render the UI depending on a call to your own DB. Hope that this works for you and sorry we don't have a perfect solution for you here out of the box!
