### ISSUE TITLE
When stream api send a notification?

### ISSUE THREAD

**Issue by mattdamon108** [GetStream/stream-chat-js#652]
Hi Team,

I implemented APNs and FCM for push notification for my react native app. It works fine and gets notifications in the foreground/background/when the app is closed. I tested it with APNs notification send utility and stream CLI push:test.

But, in the case of iOS, It seems the push notification is sent when the app is closed. When I test with stream CLI, it gets a push notification when the app is in the background too. I guess stream API starts sending a notification when a channel member seems offline or something.

How can I make my app getting a notification from stream API even though my app is in foreground or background? Any method or API to trigger to send a notification?

gz#10622

**Comment by shodgetts** [comment]
Agent comment from Vishal Narkhede in <a href='https://getstream.zendesk.com/agent/tickets/10622'>Zendesk ticket #10622</a>:<br><br>Hey Matt,

**Comment by shodgetts** [comment]
Agent comment from Vishal Narkhede in <a href='https://getstream.zendesk.com/agent/tickets/10622'>Zendesk ticket #10622</a>:<br><br>Hey Matt,

Pardon me for my previous email. One of our backend engineers will get back to you soon.

Thanks,
Vishal

**Comment by shodgetts** [comment]
Agent comment from ferhat elmas in <a href='https://getstream.zendesk.com/agent/tickets/10622'>Zendesk ticket #10622</a>:<br><br>Hey Matt,

Your guess is correct. User must be offline. Otherwise, we won't send the notification.
This behavior can't be changed for usual flow for v1 of push.
However, you can force sending via check push endpoint with message id (this is the same endpoint used in CLI push:test).
It sends the notification irrespective of online status.

That being said, in couple of weeks, v2 will be live and you will be able to customize this in app global, channel member and user global settings too.

Kind regards,
ferhat.

**Comment by nhannah** [comment]
This issue appears stale and the V2 docs for push are now available.
