### ISSUE TITLE
verifyWebhook always return false

### ISSUE THREAD

**Issue by jorgeAM** [GetStream/stream-chat-js#714]
Hello I'm using nestjs with fastify and I have to check webhook so I'm using [rawBody](https://github.com/Eomm/fastify-raw-body#readme)

in main.ts inside bootstrap function
<img width="765" alt="Captura de Pantalla 2021-07-08 a la(s) 23 01 35" src="https://user-images.githubusercontent.com/19254966/125021520-73c8cb80-e040-11eb-9d4d-6311db99cb44.png">

In controller I have access to rawBody

<img width="465" alt="Captura de Pantalla 2021-07-08 a la(s) 23 03 11" src="https://user-images.githubusercontent.com/19254966/125021626-ad99d200-e040-11eb-95bb-4a4beac32cf4.png">

in log `rawBody.toString()` logs same object `data` and `rawBody` is a Buffer

How should I verify hook? documentation isn't clear

gz#13433

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/13433'>Zendesk ticket #13433</a>:<br><br>Hi

Thanks for reaching out to us.
We will check this and come back to you soon.

Best,
<br><p><em><small>°°°</small></em></p>

**Comment by ferhatelmas** [comment]
What is the app id and api key you initialize your client? (safe to share here)?

**Comment by jorgeAM** [comment]
My App ID is `105935`
My key is `t7u7wdbxbgwy`

this is how initialize client 

<img width="804" alt="Captura de Pantalla 2021-07-09 a la(s) 09 14 57" src="https://user-images.githubusercontent.com/19254966/125091580-24ad8580-e096-11eb-9f65-2bca60c009b4.png">

**Comment by jorgeAM** [comment]
is there any update on this issue?

**Comment by ferhatelmas** [comment]
@jorgeAM I wanted to see how many keys you have in your app. That's why I had asked about api key.

Problem is documented here: https://github.com/Eomm/fastify-raw-body#raw-body-as-buffer

when `encoding` is false, it parses the body as [almost json](https://github.com/Eomm/fastify-raw-body/blob/eeb86a8b6ebccfaf8480d64a2dfd4ec412b9a95b/plugin.js#L22) but it changes the underlying bytes. For comparison, body is needed without any changes.

You might want to do something like this: https://www.fastify.io/docs/master/ContentTypeParser/#catch-all

**Comment by ferhatelmas** [comment]
I will close this ticket. If anything else is need, please reply and let us know.
