### ISSUE TITLE
Retry user connection to chat

### ISSUE THREAD

**Issue by ericlifs** [GetStream/stream-chat-js#767]
Hi everyone, how are you?

I'm having an issue with my users' connection to the chat and I want to see if there is a way of fixing it. The thing is that I'm showing the users an Error message component to the users if the `client.connectUser` fails. But I wanted to implement a "Retry" button  in that component in order to let the users re-connect to the chat. 

Is there a way of retry the users connection to the chat? Do I only have to call the `client.connectUser` again? (I have seen that "Don't do consecutive calls to connectUser" warning too). Is the connection able to reconnect by itself after some seconds? My specific issue happens when they try to connect without internet network and after some seconds they get theirs internet back again.

Thank you very much!

**Comment by mahboubii** [comment]
hey @ericlifs,

`client.connectUser` only resolves when the connection is successfully established, otherwise, it rejects. It could take few seconds for this function to resolve/reject since it retries a few times to establish the connection.

You can call `connectUser` after the first call is rejected, any subsequent calls while it still tries to connect will throw an error.

In order to achieve what you need, you can simply wrap the `connectUser` with a retryable, for example [retry](https://www.npmjs.com/package/retry) or [async-retry](https://www.npmjs.com/package/async-retry).
