### ISSUE TITLE
Have list of Users who mute current user ?

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [GetStream/stream-chat-js#784]
### Please select which package this feature is related to

stream_chat_flutter

### Which platforms would this feature impact?

iOS

### Is your feature request related to a problem?

Hi,
Im trying to:
- Disable direct dm (if current user is muted from other) => Hide user from user search

i see in the ownUser model a list of users current user muted, but not the list of users who muted current user.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deven98** [comment]
Hi, 

Just an update - we have added this feature in our internal backlog for future consideration. We will close this issue and add it as a reference to the ticket, so that we can update you once it is ready (we don’t have an ETA yet). 

Once again, thanks for bringing this to our attention and please let us know if we can help with anything else in the future.
