### ISSUE TITLE
Any way to listen for when a message is flagged?  

### ISSUE THREAD

**Issue by codekiln** [GetStream/stream-chat-js#98]
I'd like to be able to give my moderators the ability to "flag" a message and then have the message appear at the top of the chat window as a sticky message.

I've seen the [event types described in `events.js`](https://github.com/GetStream/stream-chat-js/blob/92ec8433329d33ddd9e42689a6d89ccbf2e8330a/src/events.js#L1) - is there any existing event that could be used to receive the flag event? Alternatively, would you consider adding a flag event?

**Comment by ferhatelmas** [comment]
You can add any custom data to [your messages](https://getstream.io/chat/docs/js/#send_message) and then since message is updated, you will get `message.updated` [event](https://getstream.io/chat/docs/js/#event_object) with the complete message to implement any logic you need.

**Comment by IrvingArmenta** [comment]
On this.
I know is quite outdated, but sure, you can add a property to the message and act on it, however, that is not the issue, the issue is getting/knowing when the message has being reviewed/unflagged from the moderator dashboard, `message.updated` does not get triggered when that happens, so what is the simpliest solution?
